# -*- coding: utf-8 -*-
"""mazegenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Ertthecoder/8dd29d9ec1be316aecd47a1b32795cb4/mazegenerator.ipynb

### Creating the Maze
"""

import random

# Getting maze dimensions

width = int(input("Please enter a width for your maze: "))
height = int(input("Please enter a height for your maze: "))

# Generating maze

maze = [[" " for j in range(width)] for i in range(height)]

# Generating walls on outer edges

for i in range(height):
    maze[i][0] = "#"
    maze[i][width-1] = "#"
for j in range(width):
    maze[0][j] = "#"
    maze[height-1][j] = "#"

# Generating interior walls
for i in range(1, height-1):
    for j in range(1, width-1):
        if random.randint(0, 100) < 30:
            maze[i][j] = "#"

# Setting a starting point

start_x, start_y = 1, 1
maze[start_x][start_y] = "S"

# Setting an ending point

end_x, end_y = width-2, height-2
maze[end_y][end_x] = "E"

# Printing maze

for i in range(height):
  for j in range(width):
      print(maze[i][j], end="")
  print()

import numpy as np

# Saving the maze as wished

maze_name = input("Save the maze as: ")
np.save('{}.npy'.format(maze_name), maze)